
function pesquisaLista() {
    document.getElementById("conteudoLista").innerHTML = "<H1>Estatística de Segurança Pública </H1>"
      + "<br>" 
      +"<p>Estatísticas de segurança: série histórica mensal por área de delegacia desde 01/2003 </p>" 
      + "<br>"
      + "<p>Estatísticas de segurança: série histórica mensal no estado desde 01/1991 </p>"
      + "<br>"
      + "Estatísticas de segurança: série histórica mensal no estado desde 01/2003 (taxas por 100 mil habitantes) </p>"
      + "<br>"
      + "Estatísticas de segurança: série histórica anual no estado desde 1991 (taxas por 100 mil habitantes) </p>"
      + "<br>"
      + "<p>Estatísticas de segurança: série histórica mensal por município desde 2014 </p>"
      + "<br>"
      + "<p>Estatísticas de segurança: série histórica mensal por município desde 01/2014 (taxas por 100 mil habitantes) </p>"
      + "<br>"
      + "<p> Estatísticas de segurança: série histórica anual por município desde 2014 (taxas por 100 mil habitantes)</p>"
      + "<br>"
      + "<p> Estatísticas de segurança: série histórica mensal por área de Unidade de Polícia Pacificadora (01/2007 a 06/2021)</p>"
      + "<br>"
      + "<p> Armas apreendidas: série histórica mensal por área de delegacia desde 01/2007 </p>"
      + "<br>"
      + "<p>Armas de fogo apreendidas: série histórica mensal por área de delegacia (01/2003 a 12/2006) </p>"
      + "<br>"
      + "<p> Armas de fogo apreendidas: série histórica mensal no estado (01/2000 a 12/2006)</p>"
      + "<br>"
      + "<p> Policiais mortos em serviço: série histórica mensal por área de delegacia desde 01/2003</p>"
      + "<br>"
      + "<p> Feminicídio (Lei 7.448/2016): série histórica mensal por área de delegacia desde 10/2016</p>"
      + "<br>"
      + "<p> Letalidade violenta: série histórica anual no estado desde 1991 (taxas por 100 mil habitantes)</p>"
      + "<br>"
      + "<p> Letalidade violenta: consulta interativa</p>"
      + "<br>"
      + "<p> Letalidade violenta: taxa de elucidação</p>"
      + "<br>"
      + "<p> Roubos e furtos de bicicleta (Lei 7.026/2015): série histórica desde 07/2015</p>"
      + "<br>"
      + "<p> Discriminação (Lei nº 9.276/2021): série histórica desde 07/2015</p>"
      + "<br>";
  }